### ISSUE TITLE
Support for vault ID with prompt

### ISSUE THREAD

**Issue by McAndersDK** [ipierre1/ansible-vault-vscode#33]
**Is your feature request related to a problem? Please describe.**
yeah somewhat, we want to use vault ID's but we also want to have it to prompt for the password.
it fail to do that today

**Describe the solution you'd like**
It should prompt just like it do it without the vault ID config, then prompt are defined in the list

**Describe alternatives you've considered**
not using the extension?...

**Additional context**
ansible.cfg
[default]
vault_identity_list = dev@dev_pass , nonp@prompt , prod@prompt

**Comment by ipierre1** [comment]
Hello, I just ship a new version, when no password is found by searching vault password file, it will prompt the user.
